version: "3.8"
services:
  tinystore:
    build: ./tinystore
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'store3'
      MYSQL_ALLOW_EMPTY_PASSWORD: True
    volumes:
      - ./data/mysql/db:/var/lib/mysql
    