# Generated by Django 4.0.3 on 2022-04-01 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0004_address_zip_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='place_at',
            new_name='placed_at',
        ),
    ]
