# Generated by Django 4.1.1 on 2022-09-26 08:12

from django.db import migrations, models
import storeapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0017_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='zip_code',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='storeapp/images', validators=[storeapp.validators.validate_file_size]),
        ),
    ]
